name: Deployment
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_SERVER_BASE_URL: ${{ vars.SERVER_URL }}
          envkey_SSL: ${{ vars.SSL }}
          envkey_DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: https://${{ vars.DOCKER_REGISTRY }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add SSH key to known hosts
        run: ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      
      - name: Copy Docker Compose file
        run: scp -o StrictHostKeyChecking=yes compose.yml ${{ secrets.USER }}@${{ secrets.HOST }}:${{ vars.APP_DIR }}
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
            envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            envkey_DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
            file_name: .env
            fail_on_empty: false
            sort_keys: false

      - name: Copy .env file
        run: scp -o StrictHostKeyChecking=yes .env ${{ secrets.USER }}@${{ secrets.HOST }}:${{ vars.APP_DIR }}

      - name: Deploy
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd ${{ vars.APP_DIR }}
          docker login https://${{ vars.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker compose pull
          docker compose down
          docker compose up -d  # Run in detached mode
          if [ $? -ne 0 ]; then
            echo "Docker Compose failed to start the containers"
            exit 1  # Explicitly fail the job if the command fails
          fi
          EOF
